"""Multiagente.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h_01XcPNdulJlgh3gghqchwjU6P412gF

#  Pipeline de 3 Agentes Inteligentes

**Arquitectura:**
```
Dataset CSV
     ↓
AGENTE 1 - Normalizador  →  limpia, imputa, escala, codifica
     ↓ dataset limpio
AGENTE 2 - Entrenador    →  aplica validación, entrena, selecciona modelo
     ↓ métricas + modelo
AGENTE 3 - Comunicador   →  genera reporte en lenguaje natural
```

Instalación de dependencias
"""

!pip install langchain langchain-community langchain-mistralai scikit-learn pandas numpy matplotlib seaborn -q

"""Configuración de API Key"""

import os
from google.colab import userdata

# Opción 1: desde Colab Secrets (recomendado)
try:
    os.environ["MISTRAL_API_KEY"] = userdata.get('MISTRAL_API_KEY')
    print(" API Key cargada desde Secrets")
except:
    # Opción 2: manual
    os.environ["MISTRAL_API_KEY"] = "TU_API_KEY_AQUI"
    print("Ingresá tu API Key manualmente")

"""Generación del Dataset CSV (500+ filas)"""

import pandas as pd
import numpy as np

np.random.seed(42)
N = 600  # 600 registros

categorias = ['Electrónica', 'Ropa', 'Hogar', 'Alimentos', 'Deportes']
regiones   = ['Norte', 'Sur', 'Este', 'Oeste', 'Centro']

df_raw = pd.DataFrame({
    'id_venta':       range(1, N + 1),
    'fecha':          pd.date_range('2023-01-01', periods=N, freq='D').strftime('%Y-%m-%d'),
    'categoria':      np.random.choice(categorias, N),
    'region':         np.random.choice(regiones, N),
    'cantidad':       np.random.randint(1, 50, N).astype(float),
    'precio_unitario':np.round(np.random.uniform(5, 500, N), 2),
    'descuento_pct':  np.round(np.random.uniform(0, 30, N), 1),
    'costo':          np.round(np.random.uniform(2, 300, N), 2),
    'vendedor_exp_años': np.random.randint(1, 20, N).astype(float),
    'satisfaccion_cliente': np.random.randint(1, 6, N).astype(float),
})

# Calcular ganancia (variable objetivo)
df_raw['ingreso'] = df_raw['cantidad'] * df_raw['precio_unitario'] * (1 - df_raw['descuento_pct'] / 100)
df_raw['ganancia'] = np.round(df_raw['ingreso'] - (df_raw['cantidad'] * df_raw['costo']), 2)
# Target binario: venta exitosa = ganancia > 0
df_raw['venta_exitosa'] = (df_raw['ganancia'] > 0).astype(int)

# Introducir valores faltantes (~5%)
for col in ['cantidad', 'descuento_pct', 'satisfaccion_cliente', 'vendedor_exp_años']:
    idx = np.random.choice(df_raw.index, size=int(N * 0.05), replace=False)
    df_raw.loc[idx, col] = np.nan

# Guardar CSV
df_raw.to_csv('ventas_dataset.csv', index=False)

print(f"Dataset generado: {df_raw.shape[0]} filas × {df_raw.shape[1]} columnas")
print(f"\n Primeras filas:")
df_raw.head(3)

"""---
