{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMLX4ExIfzI5apVaiDFGYH/",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/MilagrosAlonso/TP-IA/blob/main/Multiagente.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "m_ij4rG4Z2Js"
      },
      "source": [
        "# 🤖 Pipeline de 3 Agentes Inteligentes\n",
        "\n",
        "**Arquitectura:**\n",
        "```\n",
        "Dataset CSV\n",
        "     ↓\n",
        "AGENTE 1 - Normalizador  →  limpia, imputa, escala, codifica\n",
        "     ↓ dataset limpio\n",
        "AGENTE 2 - Entrenador    →  aplica validación, entrena, selecciona modelo\n",
        "     ↓ métricas + modelo\n",
        "AGENTE 3 - Comunicador   →  genera reporte en lenguaje natural\n",
        "```"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "foOAwaE-Z2Jt"
      },
      "source": [
        "## 📦 Instalación de dependencias"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "6Xlz7e1PZ2Jt",
        "outputId": "2e337840-6827-42f2-e06a-65de604311a5"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\u001b[?25l   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m0.0/2.4 MB\u001b[0m \u001b[31m?\u001b[0m eta \u001b[36m-:--:--\u001b[0m\r\u001b[2K   \u001b[91m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[91m╸\u001b[0m \u001b[32m2.4/2.4 MB\u001b[0m \u001b[31m153.7 MB/s\u001b[0m eta \u001b[36m0:00:01\u001b[0m\r\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m2.4/2.4 MB\u001b[0m \u001b[31m59.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25h\u001b[?25l   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m0.0/1.0 MB\u001b[0m \u001b[31m?\u001b[0m eta \u001b[36m-:--:--\u001b[0m\r\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.0/1.0 MB\u001b[0m \u001b[31m43.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m554.9/554.9 kB\u001b[0m \u001b[31m30.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m73.1/73.1 kB\u001b[0m \u001b[31m4.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25h\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
            "google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.\u001b[0m\u001b[31m\n",
            "\u001b[0m"
          ]
        }
      ],
      "source": [
        "!pip install langchain langchain-community langchain-mistralai scikit-learn pandas numpy matplotlib seaborn -q"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "h83ZUaWmZ2Ju"
      },
      "source": [
        "## 🔑 Configuración de API Key"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "o3gCcs6BZ2Ju",
        "outputId": "7e161fcf-64a6-41b3-93cc-0dde78f71a14"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "✅ API Key cargada desde Secrets\n"
          ]
        }
      ],
      "source": [
        "import os\n",
        "from google.colab import userdata\n",
        "\n",
        "# Opción 1: desde Colab Secrets (recomendado)\n",
        "try:\n",
        "    os.environ[\"MISTRAL_API_KEY\"] = userdata.get('MISTRAL_API_KEY')\n",
        "    print(\"✅ API Key cargada desde Secrets\")\n",
        "except:\n",
        "    # Opción 2: manual\n",
        "    os.environ[\"MISTRAL_API_KEY\"] = \"TU_API_KEY_AQUI\"\n",
        "    print(\"⚠️ Ingresá tu API Key manualmente\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "v-lTpqhTZ2Ju"
      },
      "source": [
        "## 📊 Generación del Dataset CSV (500+ filas)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 268
        },
        "id": "aOoIz2Y5Z2Ju",
        "outputId": "ae4db4ad-e0a0-4004-ca73-2cc4bf604929"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "✅ Dataset generado: 600 filas × 13 columnas\n",
            "\n",
            "📋 Primeras filas:\n"
          ]
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "   id_venta       fecha  categoria  region  cantidad  precio_unitario  \\\n",
              "0         1  2023-01-01  Alimentos    Este      46.0           385.02   \n",
              "1         2  2023-01-02   Deportes   Oeste       2.0           254.90   \n",
              "2         3  2023-01-03      Hogar  Centro      43.0           273.93   \n",
              "\n",
              "   descuento_pct   costo  vendedor_exp_años  satisfaccion_cliente  \\\n",
              "0            3.7  206.85               18.0                   5.0   \n",
              "1           22.1    9.30                2.0                   5.0   \n",
              "2            7.1   93.23               11.0                   3.0   \n",
              "\n",
              "       ingreso  ganancia  venta_exitosa  \n",
              "0  17055.61596   7540.52              1  \n",
              "1    397.13420    378.53              1  \n",
              "2  10942.68171   6933.79              1  "
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-2e8ddf63-93e1-4d59-a3c5-514f504284e4\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>id_venta</th>\n",
              "      <th>fecha</th>\n",
              "      <th>categoria</th>\n",
              "      <th>region</th>\n",
              "      <th>cantidad</th>\n",
              "      <th>precio_unitario</th>\n",
              "      <th>descuento_pct</th>\n",
              "      <th>costo</th>\n",
              "      <th>vendedor_exp_años</th>\n",
              "      <th>satisfaccion_cliente</th>\n",
              "      <th>ingreso</th>\n",
              "      <th>ganancia</th>\n",
              "      <th>venta_exitosa</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>1</td>\n",
              "      <td>2023-01-01</td>\n",
              "      <td>Alimentos</td>\n",
              "      <td>Este</td>\n",
              "      <td>46.0</td>\n",
              "      <td>385.02</td>\n",
              "      <td>3.7</td>\n",
              "      <td>206.85</td>\n",
              "      <td>18.0</td>\n",
              "      <td>5.0</td>\n",
              "      <td>17055.61596</td>\n",
              "      <td>7540.52</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>2</td>\n",
              "      <td>2023-01-02</td>\n",
              "      <td>Deportes</td>\n",
              "      <td>Oeste</td>\n",
              "      <td>2.0</td>\n",
              "      <td>254.90</td>\n",
              "      <td>22.1</td>\n",
              "      <td>9.30</td>\n",
              "      <td>2.0</td>\n",
              "      <td>5.0</td>\n",
              "      <td>397.13420</td>\n",
              "      <td>378.53</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>3</td>\n",
              "      <td>2023-01-03</td>\n",
              "      <td>Hogar</td>\n",
              "      <td>Centro</td>\n",
              "      <td>43.0</td>\n",
              "      <td>273.93</td>\n",
              "      <td>7.1</td>\n",
              "      <td>93.23</td>\n",
              "      <td>11.0</td>\n",
              "      <td>3.0</td>\n",
              "      <td>10942.68171</td>\n",
              "      <td>6933.79</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-2e8ddf63-93e1-4d59-a3c5-514f504284e4')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-2e8ddf63-93e1-4d59-a3c5-514f504284e4 button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-2e8ddf63-93e1-4d59-a3c5-514f504284e4');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "variable_name": "df_raw",
              "summary": "{\n  \"name\": \"df_raw\",\n  \"rows\": 600,\n  \"fields\": [\n    {\n      \"column\": \"id_venta\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 173,\n        \"min\": 1,\n        \"max\": 600,\n        \"num_unique_values\": 600,\n        \"samples\": [\n          111,\n          420,\n          566\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"fecha\",\n      \"properties\": {\n        \"dtype\": \"object\",\n        \"num_unique_values\": 600,\n        \"samples\": [\n          \"2023-04-21\",\n          \"2024-02-24\",\n          \"2024-07-19\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"categoria\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 5,\n        \"samples\": [\n          \"Deportes\",\n          \"Electr\\u00f3nica\",\n          \"Hogar\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"region\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 5,\n        \"samples\": [\n          \"Oeste\",\n          \"Sur\",\n          \"Centro\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"cantidad\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 13.827107441335915,\n        \"min\": 1.0,\n        \"max\": 49.0,\n        \"num_unique_values\": 49,\n        \"samples\": [\n          34.0,\n          13.0,\n          28.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"precio_unitario\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 137.39121799308148,\n        \"min\": 5.16,\n        \"max\": 497.76,\n        \"num_unique_values\": 598,\n        \"samples\": [\n          302.3,\n          194.35,\n          237.81\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"descuento_pct\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 8.894047056480439,\n        \"min\": 0.0,\n        \"max\": 30.0,\n        \"num_unique_values\": 253,\n        \"samples\": [\n          20.2,\n          22.0,\n          20.5\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"costo\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 85.6684208018449,\n        \"min\": 2.13,\n        \"max\": 299.86,\n        \"num_unique_values\": 596,\n        \"samples\": [\n          194.09,\n          191.69,\n          59.05\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"vendedor_exp_a\\u00f1os\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 5.32398550263692,\n        \"min\": 1.0,\n        \"max\": 19.0,\n        \"num_unique_values\": 19,\n        \"samples\": [\n          18.0,\n          4.0,\n          3.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"satisfaccion_cliente\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1.3938520966201837,\n        \"min\": 1.0,\n        \"max\": 5.0,\n        \"num_unique_values\": 5,\n        \"samples\": [\n          3.0,\n          4.0,\n          1.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"ingreso\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 4510.774749118954,\n        \"min\": 59.80260000000001,\n        \"max\": 21596.54,\n        \"num_unique_values\": 600,\n        \"samples\": [\n          10944.4692,\n          4718.095200000001,\n          1256.45917\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"ganancia\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 4426.612920113116,\n        \"min\": -11124.05,\n        \"max\": 18316.08,\n        \"num_unique_values\": 600,\n        \"samples\": [\n          1853.15,\n          880.67,\n          63.26\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"venta_exitosa\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 1,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          0,\n          1\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {},
          "execution_count": 3
        }
      ],
      "source": [
        "import pandas as pd\n",
        "import numpy as np\n",
        "\n",
        "np.random.seed(42)\n",
        "N = 600  # 600 registros\n",
        "\n",
        "categorias = ['Electrónica', 'Ropa', 'Hogar', 'Alimentos', 'Deportes']\n",
        "regiones   = ['Norte', 'Sur', 'Este', 'Oeste', 'Centro']\n",
        "\n",
        "df_raw = pd.DataFrame({\n",
        "    'id_venta':       range(1, N + 1),\n",
        "    'fecha':          pd.date_range('2023-01-01', periods=N, freq='D').strftime('%Y-%m-%d'),\n",
        "    'categoria':      np.random.choice(categorias, N),\n",
        "    'region':         np.random.choice(regiones, N),\n",
        "    'cantidad':       np.random.randint(1, 50, N).astype(float),\n",
        "    'precio_unitario':np.round(np.random.uniform(5, 500, N), 2),\n",
        "    'descuento_pct':  np.round(np.random.uniform(0, 30, N), 1),\n",
        "    'costo':          np.round(np.random.uniform(2, 300, N), 2),\n",
        "    'vendedor_exp_años': np.random.randint(1, 20, N).astype(float),\n",
        "    'satisfaccion_cliente': np.random.randint(1, 6, N).astype(float),\n",
        "})\n",
        "\n",
        "# Calcular ganancia (variable objetivo)\n",
        "df_raw['ingreso'] = df_raw['cantidad'] * df_raw['precio_unitario'] * (1 - df_raw['descuento_pct'] / 100)\n",
        "df_raw['ganancia'] = np.round(df_raw['ingreso'] - (df_raw['cantidad'] * df_raw['costo']), 2)\n",
        "# Target binario: venta exitosa = ganancia > 0\n",
        "df_raw['venta_exitosa'] = (df_raw['ganancia'] > 0).astype(int)\n",
        "\n",
        "# Introducir valores faltantes (~5%)\n",
        "for col in ['cantidad', 'descuento_pct', 'satisfaccion_cliente', 'vendedor_exp_años']:\n",
        "    idx = np.random.choice(df_raw.index, size=int(N * 0.05), replace=False)\n",
        "    df_raw.loc[idx, col] = np.nan\n",
        "\n",
        "# Guardar CSV\n",
        "df_raw.to_csv('ventas_dataset.csv', index=False)\n",
        "\n",
        "print(f\"✅ Dataset generado: {df_raw.shape[0]} filas × {df_raw.shape[1]} columnas\")\n",
        "print(f\"\\n📋 Primeras filas:\")\n",
        "df_raw.head(3)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "jwINb4TvZ2Jv"
      },
      "source": [
        "---\n",
        "## 🧹 AGENTE 1 — Normalizador\n",
        "> **Función:** Limpia, imputa, escala y codifica el dataset"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "e53hmSVLZ2Jv"
      },
      "outputs": [],
      "source": [
        "import json\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "from sklearn.preprocessing import StandardScaler, LabelEncoder\n",
        "from langchain_mistralai import ChatMistralAI\n",
        "from langchain.schema import HumanMessage, SystemMessage\n",
        "\n",
        "# ── LLM compartido ──────────────────────────────────────────────────────────\n",
        "llm = ChatMistralAI(model=\"mistral-small-latest\", temperature=0.2)\n",
        "\n",
        "# ── Clase Agente 1 ──────────────────────────────────────────────────────────\n",
        "class AgenteNormalizador:\n",
        "    \"\"\"AGENTE 1: limpia, imputa, escala y codifica el dataset CSV.\"\"\"\n",
        "\n",
        "    def __init__(self, llm):\n",
        "        self.llm = llm\n",
        "        self.scaler = StandardScaler()\n",
        "        self.label_encoders = {}\n",
        "        self.reporte = {}\n",
        "\n",
        "    # ── 1. Análisis inicial con LLM ──────────────────────────────────────\n",
        "    def analizar_con_llm(self, info_dataset: str) -> str:\n",
        "        resp = self.llm.invoke([\n",
        "            SystemMessage(content=\"Eres un experto en limpieza de datos. Respondé en español.\"),\n",
        "            HumanMessage(content=f\"\"\"\n",
        "Analizá este dataset y decí qué pasos de limpieza son necesarios:\n",
        "{info_dataset}\n",
        "Listá brevemente: columnas con nulos, columnas categóricas a codificar y columnas numéricas a escalar.\n",
        "\"\"\")\n",
        "        ])\n",
        "        return resp.content\n",
        "\n",
        "    # ── 2. Limpieza e imputación ─────────────────────────────────────────\n",
        "    def limpiar_e_imputar(self, df: pd.DataFrame) -> pd.DataFrame:\n",
        "        df = df.copy()\n",
        "        nulos_antes = df.isnull().sum().sum()\n",
        "\n",
        "        # Eliminar duplicados\n",
        "        df.drop_duplicates(inplace=True)\n",
        "\n",
        "        # Imputar numéricos con mediana\n",
        "        num_cols = df.select_dtypes(include=[np.number]).columns\n",
        "        for col in num_cols:\n",
        "            if df[col].isnull().sum() > 0:\n",
        "                df[col].fillna(df[col].median(), inplace=True)\n",
        "\n",
        "        # Imputar categóricos con moda\n",
        "        cat_cols = df.select_dtypes(include=['object']).columns\n",
        "        for col in cat_cols:\n",
        "            if df[col].isnull().sum() > 0:\n",
        "                df[col].fillna(df[col].mode()[0], inplace=True)\n",
        "\n",
        "        self.reporte['nulos_antes'] = int(nulos_antes)\n",
        "        self.reporte['nulos_despues'] = int(df.isnull().sum().sum())\n",
        "        self.reporte['filas_finales'] = len(df)\n",
        "        return df\n",
        "\n",
        "    # ── 3. Codificación de categóricas ──────────────────────────────────\n",
        "    def codificar(self, df: pd.DataFrame, cols_categoricas: list) -> pd.DataFrame:\n",
        "        df = df.copy()\n",
        "        for col in cols_categoricas:\n",
        "            if col in df.columns:\n",
        "                le = LabelEncoder()\n",
        "                df[col + '_enc'] = le.fit_transform(df[col].astype(str))\n",
        "                self.label_encoders[col] = le\n",
        "        self.reporte['columnas_codificadas'] = cols_categoricas\n",
        "        return df\n",
        "\n",
        "    # ── 4. Escalado de numéricas ─────────────────────────────────────────\n",
        "    def escalar(self, df: pd.DataFrame, cols_numericas: list) -> pd.DataFrame:\n",
        "        df = df.copy()\n",
        "        cols_existentes = [c for c in cols_numericas if c in df.columns]\n",
        "        df[cols_existentes] = self.scaler.fit_transform(df[cols_existentes])\n",
        "        self.reporte['columnas_escaladas'] = cols_existentes\n",
        "        return df\n",
        "\n",
        "    # ── Pipeline completo ────────────────────────────────────────────────\n",
        "    def ejecutar(self, ruta_csv: str) -> pd.DataFrame:\n",
        "        print(\"=\"*60)\n",
        "        print(\"🧹 AGENTE 1 — NORMALIZADOR\")\n",
        "        print(\"=\"*60)\n",
        "\n",
        "        df = pd.read_csv(ruta_csv)\n",
        "        print(f\"📥 Dataset cargado: {df.shape}\")\n",
        "\n",
        "        # Análisis LLM\n",
        "        info = f\"Columnas: {list(df.columns)}\\nNulos por columna:\\n{df.isnull().sum().to_dict()}\\nTipos:\\n{df.dtypes.to_dict()}\"\n",
        "        print(\"\\n🤖 Análisis del LLM:\")\n",
        "        analisis = self.analizar_con_llm(info)\n",
        "        print(analisis)\n",
        "\n",
        "        # Limpieza\n",
        "        df = self.limpiar_e_imputar(df)\n",
        "        print(f\"\\n✅ Imputación completada | Nulos antes: {self.reporte['nulos_antes']} → después: {self.reporte['nulos_despues']}\")\n",
        "\n",
        "        # Columnas a procesar\n",
        "        cols_cat = ['categoria', 'region']\n",
        "        cols_num = ['cantidad', 'precio_unitario', 'descuento_pct', 'costo',\n",
        "                    'vendedor_exp_años', 'satisfaccion_cliente']\n",
        "\n",
        "        # Codificación\n",
        "        df = self.codificar(df, cols_cat)\n",
        "        print(f\"✅ Columnas codificadas: {cols_cat}\")\n",
        "\n",
        "        # Escalado\n",
        "        df = self.escalar(df, cols_num)\n",
        "        print(f\"✅ Columnas escaladas: {cols_num}\")\n",
        "\n",
        "        # Guardar dataset limpio\n",
        "        df.to_csv('ventas_limpio.csv', index=False)\n",
        "        print(f\"\\n💾 Dataset limpio guardado: ventas_limpio.csv ({df.shape})\")\n",
        "        print(\"=\"*60)\n",
        "\n",
        "        return df, self.reporte\n",
        "\n",
        "# ── Ejecutar Agente 1 ────────────────────────────────────────────────────────\n",
        "agente1 = AgenteNormalizador(llm)\n",
        "df_limpio, reporte_ag1 = agente1.ejecutar('ventas_dataset.csv')"
      ]
    }
  ]
}