{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMWTtAR9mO1fiQ+aJ4GV+Wv",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/MilagrosAlonso/TP-IA/blob/main/Multiagente.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "m_ij4rG4Z2Js"
      },
      "source": [
        "# 🤖 Pipeline de 3 Agentes Inteligentes\n",
        "\n",
        "**Arquitectura:**\n",
        "```\n",
        "Dataset CSV\n",
        "     ↓\n",
        "AGENTE 1 - Normalizador  →  limpia, imputa, escala, codifica\n",
        "     ↓ dataset limpio\n",
        "AGENTE 2 - Entrenador    →  aplica validación, entrena, selecciona modelo\n",
        "     ↓ métricas + modelo\n",
        "AGENTE 3 - Comunicador   →  genera reporte en lenguaje natural\n",
        "```"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "foOAwaE-Z2Jt"
      },
      "source": [
        "## 📦 Instalación de dependencias"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "6Xlz7e1PZ2Jt",
        "outputId": "2e337840-6827-42f2-e06a-65de604311a5"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\u001b[?25l   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m0.0/2.4 MB\u001b[0m \u001b[31m?\u001b[0m eta \u001b[36m-:--:--\u001b[0m\r\u001b[2K   \u001b[91m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[91m╸\u001b[0m \u001b[32m2.4/2.4 MB\u001b[0m \u001b[31m153.7 MB/s\u001b[0m eta \u001b[36m0:00:01\u001b[0m\r\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m2.4/2.4 MB\u001b[0m \u001b[31m59.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25h\u001b[?25l   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m0.0/1.0 MB\u001b[0m \u001b[31m?\u001b[0m eta \u001b[36m-:--:--\u001b[0m\r\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.0/1.0 MB\u001b[0m \u001b[31m43.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m554.9/554.9 kB\u001b[0m \u001b[31m30.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m73.1/73.1 kB\u001b[0m \u001b[31m4.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25h\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
            "google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.\u001b[0m\u001b[31m\n",
            "\u001b[0m"
          ]
        }
      ],
      "source": [
        "!pip install langchain langchain-community langchain-mistralai scikit-learn pandas numpy matplotlib seaborn -q"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "h83ZUaWmZ2Ju"
      },
      "source": [
        "## 🔑 Configuración de API Key"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "o3gCcs6BZ2Ju",
        "outputId": "7e161fcf-64a6-41b3-93cc-0dde78f71a14"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "✅ API Key cargada desde Secrets\n"
          ]
        }
      ],
      "source": [
        "import os\n",
        "from google.colab import userdata\n",
        "\n",
        "# Opción 1: desde Colab Secrets (recomendado)\n",
        "try:\n",
        "    os.environ[\"MISTRAL_API_KEY\"] = userdata.get('MISTRAL_API_KEY')\n",
        "    print(\"✅ API Key cargada desde Secrets\")\n",
        "except:\n",
        "    # Opción 2: manual\n",
        "    os.environ[\"MISTRAL_API_KEY\"] = \"TU_API_KEY_AQUI\"\n",
        "    print(\"⚠️ Ingresá tu API Key manualmente\")"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "v-lTpqhTZ2Ju"
      },
      "source": [
        "## 📊 Generación del Dataset CSV (500+ filas)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 268
        },
        "id": "aOoIz2Y5Z2Ju",
        "outputId": "ae4db4ad-e0a0-4004-ca73-2cc4bf604929"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "✅ Dataset generado: 600 filas × 13 columnas\n",
            "\n",
            "📋 Primeras filas:\n"
          ]
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "   id_venta       fecha  categoria  region  cantidad  precio_unitario  \\\n",
              "0         1  2023-01-01  Alimentos    Este      46.0           385.02   \n",
              "1         2  2023-01-02   Deportes   Oeste       2.0           254.90   \n",
              "2         3  2023-01-03      Hogar  Centro      43.0           273.93   \n",
              "\n",
              "   descuento_pct   costo  vendedor_exp_años  satisfaccion_cliente  \\\n",
              "0            3.7  206.85               18.0                   5.0   \n",
              "1           22.1    9.30                2.0                   5.0   \n",
              "2            7.1   93.23               11.0                   3.0   \n",
              "\n",
              "       ingreso  ganancia  venta_exitosa  \n",
              "0  17055.61596   7540.52              1  \n",
              "1    397.13420    378.53              1  \n",
              "2  10942.68171   6933.79              1  "
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-2e8ddf63-93e1-4d59-a3c5-514f504284e4\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>id_venta</th>\n",
              "      <th>fecha</th>\n",
              "      <th>categoria</th>\n",
              "      <th>region</th>\n",
              "      <th>cantidad</th>\n",
              "      <th>precio_unitario</th>\n",
              "      <th>descuento_pct</th>\n",
              "      <th>costo</th>\n",
              "      <th>vendedor_exp_años</th>\n",
              "      <th>satisfaccion_cliente</th>\n",
              "      <th>ingreso</th>\n",
              "      <th>ganancia</th>\n",
              "      <th>venta_exitosa</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>1</td>\n",
              "      <td>2023-01-01</td>\n",
              "      <td>Alimentos</td>\n",
              "      <td>Este</td>\n",
              "      <td>46.0</td>\n",
              "      <td>385.02</td>\n",
              "      <td>3.7</td>\n",
              "      <td>206.85</td>\n",
              "      <td>18.0</td>\n",
              "      <td>5.0</td>\n",
              "      <td>17055.61596</td>\n",
              "      <td>7540.52</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>2</td>\n",
              "      <td>2023-01-02</td>\n",
              "      <td>Deportes</td>\n",
              "      <td>Oeste</td>\n",
              "      <td>2.0</td>\n",
              "      <td>254.90</td>\n",
              "      <td>22.1</td>\n",
              "      <td>9.30</td>\n",
              "      <td>2.0</td>\n",
              "      <td>5.0</td>\n",
              "      <td>397.13420</td>\n",
              "      <td>378.53</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>3</td>\n",
              "      <td>2023-01-03</td>\n",
              "      <td>Hogar</td>\n",
              "      <td>Centro</td>\n",
              "      <td>43.0</td>\n",
              "      <td>273.93</td>\n",
              "      <td>7.1</td>\n",
              "      <td>93.23</td>\n",
              "      <td>11.0</td>\n",
              "      <td>3.0</td>\n",
              "      <td>10942.68171</td>\n",
              "      <td>6933.79</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-2e8ddf63-93e1-4d59-a3c5-514f504284e4')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-2e8ddf63-93e1-4d59-a3c5-514f504284e4 button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-2e8ddf63-93e1-4d59-a3c5-514f504284e4');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "variable_name": "df_raw",
              "summary": "{\n  \"name\": \"df_raw\",\n  \"rows\": 600,\n  \"fields\": [\n    {\n      \"column\": \"id_venta\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 173,\n        \"min\": 1,\n        \"max\": 600,\n        \"num_unique_values\": 600,\n        \"samples\": [\n          111,\n          420,\n          566\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"fecha\",\n      \"properties\": {\n        \"dtype\": \"object\",\n        \"num_unique_values\": 600,\n        \"samples\": [\n          \"2023-04-21\",\n          \"2024-02-24\",\n          \"2024-07-19\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"categoria\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 5,\n        \"samples\": [\n          \"Deportes\",\n          \"Electr\\u00f3nica\",\n          \"Hogar\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"region\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 5,\n        \"samples\": [\n          \"Oeste\",\n          \"Sur\",\n          \"Centro\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"cantidad\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 13.827107441335915,\n        \"min\": 1.0,\n        \"max\": 49.0,\n        \"num_unique_values\": 49,\n        \"samples\": [\n          34.0,\n          13.0,\n          28.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"precio_unitario\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 137.39121799308148,\n        \"min\": 5.16,\n        \"max\": 497.76,\n        \"num_unique_values\": 598,\n        \"samples\": [\n          302.3,\n          194.35,\n          237.81\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"descuento_pct\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 8.894047056480439,\n        \"min\": 0.0,\n        \"max\": 30.0,\n        \"num_unique_values\": 253,\n        \"samples\": [\n          20.2,\n          22.0,\n          20.5\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"costo\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 85.6684208018449,\n        \"min\": 2.13,\n        \"max\": 299.86,\n        \"num_unique_values\": 596,\n        \"samples\": [\n          194.09,\n          191.69,\n          59.05\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"vendedor_exp_a\\u00f1os\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 5.32398550263692,\n        \"min\": 1.0,\n        \"max\": 19.0,\n        \"num_unique_values\": 19,\n        \"samples\": [\n          18.0,\n          4.0,\n          3.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"satisfaccion_cliente\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1.3938520966201837,\n        \"min\": 1.0,\n        \"max\": 5.0,\n        \"num_unique_values\": 5,\n        \"samples\": [\n          3.0,\n          4.0,\n          1.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"ingreso\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 4510.774749118954,\n        \"min\": 59.80260000000001,\n        \"max\": 21596.54,\n        \"num_unique_values\": 600,\n        \"samples\": [\n          10944.4692,\n          4718.095200000001,\n          1256.45917\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"ganancia\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 4426.612920113116,\n        \"min\": -11124.05,\n        \"max\": 18316.08,\n        \"num_unique_values\": 600,\n        \"samples\": [\n          1853.15,\n          880.67,\n          63.26\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"venta_exitosa\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 1,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          0,\n          1\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {},
          "execution_count": 3
        }
      ],
      "source": [
        "import pandas as pd\n",
        "import numpy as np\n",
        "\n",
        "np.random.seed(42)\n",
        "N = 600  # 600 registros\n",
        "\n",
        "categorias = ['Electrónica', 'Ropa', 'Hogar', 'Alimentos', 'Deportes']\n",
        "regiones   = ['Norte', 'Sur', 'Este', 'Oeste', 'Centro']\n",
        "\n",
        "df_raw = pd.DataFrame({\n",
        "    'id_venta':       range(1, N + 1),\n",
        "    'fecha':          pd.date_range('2023-01-01', periods=N, freq='D').strftime('%Y-%m-%d'),\n",
        "    'categoria':      np.random.choice(categorias, N),\n",
        "    'region':         np.random.choice(regiones, N),\n",
        "    'cantidad':       np.random.randint(1, 50, N).astype(float),\n",
        "    'precio_unitario':np.round(np.random.uniform(5, 500, N), 2),\n",
        "    'descuento_pct':  np.round(np.random.uniform(0, 30, N), 1),\n",
        "    'costo':          np.round(np.random.uniform(2, 300, N), 2),\n",
        "    'vendedor_exp_años': np.random.randint(1, 20, N).astype(float),\n",
        "    'satisfaccion_cliente': np.random.randint(1, 6, N).astype(float),\n",
        "})\n",
        "\n",
        "# Calcular ganancia (variable objetivo)\n",
        "df_raw['ingreso'] = df_raw['cantidad'] * df_raw['precio_unitario'] * (1 - df_raw['descuento_pct'] / 100)\n",
        "df_raw['ganancia'] = np.round(df_raw['ingreso'] - (df_raw['cantidad'] * df_raw['costo']), 2)\n",
        "# Target binario: venta exitosa = ganancia > 0\n",
        "df_raw['venta_exitosa'] = (df_raw['ganancia'] > 0).astype(int)\n",
        "\n",
        "# Introducir valores faltantes (~5%)\n",
        "for col in ['cantidad', 'descuento_pct', 'satisfaccion_cliente', 'vendedor_exp_años']:\n",
        "    idx = np.random.choice(df_raw.index, size=int(N * 0.05), replace=False)\n",
        "    df_raw.loc[idx, col] = np.nan\n",
        "\n",
        "# Guardar CSV\n",
        "df_raw.to_csv('ventas_dataset.csv', index=False)\n",
        "\n",
        "print(f\"✅ Dataset generado: {df_raw.shape[0]} filas × {df_raw.shape[1]} columnas\")\n",
        "print(f\"\\n📋 Primeras filas:\")\n",
        "df_raw.head(3)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "jwINb4TvZ2Jv"
      },
      "source": [
        "---\n",
        "## 🧹 AGENTE 1 — Normalizador\n",
        "> **Función:** Limpia, imputa, escala y codifica el dataset"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "e53hmSVLZ2Jv"
      },
      "outputs": [],
      "source": [
        "import json\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "from sklearn.preprocessing import StandardScaler, LabelEncoder\n",
        "from langchain_mistralai import ChatMistralAI\n",
        "from langchain.schema import HumanMessage, SystemMessage\n",
        "\n",
        "# ── LLM compartido ──────────────────────────────────────────────────────────\n",
        "llm = ChatMistralAI(model=\"mistral-small-latest\", temperature=0.2)\n",
        "\n",
        "# ── Clase Agente 1 ──────────────────────────────────────────────────────────\n",
        "class AgenteNormalizador:\n",
        "    \"\"\"AGENTE 1: limpia, imputa, escala y codifica el dataset CSV.\"\"\"\n",
        "\n",
        "    def __init__(self, llm):\n",
        "        self.llm = llm\n",
        "        self.scaler = StandardScaler()\n",
        "        self.label_encoders = {}\n",
        "        self.reporte = {}\n",
        "\n",
        "    # ── 1. Análisis inicial con LLM ──────────────────────────────────────\n",
        "    def analizar_con_llm(self, info_dataset: str) -> str:\n",
        "        resp = self.llm.invoke([\n",
        "            SystemMessage(content=\"Eres un experto en limpieza de datos. Respondé en español.\"),\n",
        "            HumanMessage(content=f\"\"\"\n",
        "Analizá este dataset y decí qué pasos de limpieza son necesarios:\n",
        "{info_dataset}\n",
        "Listá brevemente: columnas con nulos, columnas categóricas a codificar y columnas numéricas a escalar.\n",
        "\"\"\")\n",
        "        ])\n",
        "        return resp.content\n",
        "\n",
        "    # ── 2. Limpieza e imputación ─────────────────────────────────────────\n",
        "    def limpiar_e_imputar(self, df: pd.DataFrame) -> pd.DataFrame:\n",
        "        df = df.copy()\n",
        "        nulos_antes = df.isnull().sum().sum()\n",
        "\n",
        "        # Eliminar duplicados\n",
        "        df.drop_duplicates(inplace=True)\n",
        "\n",
        "        # Imputar numéricos con mediana\n",
        "        num_cols = df.select_dtypes(include=[np.number]).columns\n",
        "        for col in num_cols:\n",
        "            if df[col].isnull().sum() > 0:\n",
        "                df[col].fillna(df[col].median(), inplace=True)\n",
        "\n",
        "        # Imputar categóricos con moda\n",
        "        cat_cols = df.select_dtypes(include=['object']).columns\n",
        "        for col in cat_cols:\n",
        "            if df[col].isnull().sum() > 0:\n",
        "                df[col].fillna(df[col].mode()[0], inplace=True)\n",
        "\n",
        "        self.reporte['nulos_antes'] = int(nulos_antes)\n",
        "        self.reporte['nulos_despues'] = int(df.isnull().sum().sum())\n",
        "        self.reporte['filas_finales'] = len(df)\n",
        "        return df\n",
        "\n",
        "    # ── 3. Codificación de categóricas ──────────────────────────────────\n",
        "    def codificar(self, df: pd.DataFrame, cols_categoricas: list) -> pd.DataFrame:\n",
        "        df = df.copy()\n",
        "        for col in cols_categoricas:\n",
        "            if col in df.columns:\n",
        "                le = LabelEncoder()\n",
        "                df[col + '_enc'] = le.fit_transform(df[col].astype(str))\n",
        "                self.label_encoders[col] = le\n",
        "        self.reporte['columnas_codificadas'] = cols_categoricas\n",
        "        return df\n",
        "\n",
        "    # ── 4. Escalado de numéricas ─────────────────────────────────────────\n",
        "    def escalar(self, df: pd.DataFrame, cols_numericas: list) -> pd.DataFrame:\n",
        "        df = df.copy()\n",
        "        cols_existentes = [c for c in cols_numericas if c in df.columns]\n",
        "        df[cols_existentes] = self.scaler.fit_transform(df[cols_existentes])\n",
        "        self.reporte['columnas_escaladas'] = cols_existentes\n",
        "        return df\n",
        "\n",
        "    # ── Pipeline completo ────────────────────────────────────────────────\n",
        "    def ejecutar(self, ruta_csv: str) -> pd.DataFrame:\n",
        "        print(\"=\"*60)\n",
        "        print(\"🧹 AGENTE 1 — NORMALIZADOR\")\n",
        "        print(\"=\"*60)\n",
        "\n",
        "        df = pd.read_csv(ruta_csv)\n",
        "        print(f\"📥 Dataset cargado: {df.shape}\")\n",
        "\n",
        "        # Análisis LLM\n",
        "        info = f\"Columnas: {list(df.columns)}\\nNulos por columna:\\n{df.isnull().sum().to_dict()}\\nTipos:\\n{df.dtypes.to_dict()}\"\n",
        "        print(\"\\n🤖 Análisis del LLM:\")\n",
        "        analisis = self.analizar_con_llm(info)\n",
        "        print(analisis)\n",
        "\n",
        "        # Limpieza\n",
        "        df = self.limpiar_e_imputar(df)\n",
        "        print(f\"\\n✅ Imputación completada | Nulos antes: {self.reporte['nulos_antes']} → después: {self.reporte['nulos_despues']}\")\n",
        "\n",
        "        # Columnas a procesar\n",
        "        cols_cat = ['categoria', 'region']\n",
        "        cols_num = ['cantidad', 'precio_unitario', 'descuento_pct', 'costo',\n",
        "                    'vendedor_exp_años', 'satisfaccion_cliente']\n",
        "\n",
        "        # Codificación\n",
        "        df = self.codificar(df, cols_cat)\n",
        "        print(f\"✅ Columnas codificadas: {cols_cat}\")\n",
        "\n",
        "        # Escalado\n",
        "        df = self.escalar(df, cols_num)\n",
        "        print(f\"✅ Columnas escaladas: {cols_num}\")\n",
        "\n",
        "        # Guardar dataset limpio\n",
        "        df.to_csv('ventas_limpio.csv', index=False)\n",
        "        print(f\"\\n💾 Dataset limpio guardado: ventas_limpio.csv ({df.shape})\")\n",
        "        print(\"=\"*60)\n",
        "\n",
        "        return df, self.reporte\n",
        "\n",
        "# ── Ejecutar Agente 1 ────────────────────────────────────────────────────────\n",
        "agente1 = AgenteNormalizador(llm)\n",
        "df_limpio, reporte_ag1 = agente1.ejecutar('ventas_dataset.csv')"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "P7cpgqxGZ2Jv"
      },
      "source": [
        "---\n",
        "## 🏋️ AGENTE 2 — Entrenador\n",
        "> **Función:** Aplica validación cruzada, entrena modelos y selecciona el mejor"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "3FTvqYLfZ2Jw",
        "outputId": "890cdb6a-9549-4f22-aabd-5e9e544abf73"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "============================================================\n",
            "🏋️  AGENTE 2 — ENTRENADOR\n",
            "============================================================\n",
            "\n",
            "🤖 Recomendación de features del LLM:\n",
            "Para predecir **venta_exitosa** (binario) en tu dataset, seleccionaría las siguientes columnas como **features**, agrupadas por tipo y justificando su relevancia:\n",
            "\n",
            "---\n",
            "\n",
            "### **1. Features temporales (relacionadas con el tiempo)**\n",
            "- **`fecha`**\n",
            "  - *Justificación*: Podría extraerse información como **día de la semana**, **mes**, **trimestre** o **estacionalidad** (ej.: ventas navideñas). La temporalidad suele impactar en el éxito de una venta.\n",
            "  - *Transformación*: Convertir a datetime y extraer características como `dia_semana`, `mes`, `es_fin_semana`, etc.\n",
            "\n",
            "---\n",
            "\n",
            "### **2. Features categóricas (variables cualitativas)**\n",
            "- **`categoria`** / **`categoria_enc`**\n",
            "  - *Justificación*: Algunas categorías pueden tener mayor tasa de éxito (ej.: productos premium vs. básicos).\n",
            "  - *Nota*: Si `categoria_enc` ya está codificada (ej.: one-hot encoding), úsala directamente. Si no, aplica encoding (One-Hot, Target Encoding, etc.).\n",
            "\n",
            "- **`region`** / **`region_enc`**\n",
            "  - *Justificación*: La región puede influir en el éxito por factores demográficos, económicos o logísticos (ej.: zonas urbanas vs. rurales).\n",
            "  - *Nota*: Similar a `categoria`, usa la versión codificada si está disponible.\n",
            "\n",
            "- **`vendedor_exp_años`**\n",
            "  - *Justificación*: La experiencia del vendedor suele correlacionar con mayores ventas exitosas (mayor habilidad para cerrar tratos).\n",
            "\n",
            "---\n",
            "\n",
            "### **3. Features numéricas (variables cuantitativas)**\n",
            "- **`cantidad`**\n",
            "  - *Justificación*: Ventas con mayor cantidad de productos pueden tener mayor probabilidad de éxito (ej.: descuentos por volumen).\n",
            "\n",
            "- **`precio_unitario`**\n",
            "  - *Justificación*: Precios muy altos/bajos pueden afectar la decisión de compra. Podría normalizarse o discretizarse.\n",
            "\n",
            "- **`descuento_pct`**\n",
            "  - *Justificación*: Descuentos altos pueden aumentar la probabilidad de éxito (pero también reducir ganancias). Analizar su relación con el target.\n",
            "\n",
            "- **`costo`**\n",
            "  - *Justificación*: Costos elevados podrían reducir la ganancia neta, afectando indirectamente el éxito de la venta.\n",
            "\n",
            "- **`ingreso`** y **`ganancia`**\n",
            "  - *Justificación*: Variables clave para predecir éxito. Una venta con alto ingreso/ganancia es más probable que sea exitosa.\n",
            "  - *Nota*: `ganancia` es especialmente relevante, ya que combina `precio_unitario`, `costo` y `cantidad`.\n",
            "\n",
            "- **`satisfaccion_cliente`**\n",
            "  - *Justificación*: Una alta satisfacción previa (o en ventas anteriores) puede aumentar la probabilidad de éxito en la venta actual.\n",
            "  - *Nota*: Si es una métrica histórica, podría requerir ingeniería de features (ej.: promedio móvil).\n",
            "\n",
            "---\n",
            "\n",
            "### **4. Features derivadas (ingeniería de features)**\n",
            "- **`precio_total`** = `cantidad` × `precio_unitario`\n",
            "  - *Justificación*: Combina dos features clave en una sola métrica.\n",
            "\n",
            "- **`ganancia_pct`** = (`ganancia` / `ingreso`) × 100\n",
            "  - *Justificación*: La rentabilidad porcentual puede ser más informativa que el valor absoluto.\n",
            "\n",
            "- **`descuento_absoluto`** = `precio_unitario` × (`descuento_pct` / 100)\n",
            "  - *Justificación*: El descuento en términos monetarios puede ser más interpretable.\n",
            "\n",
            "- **`es_venta_recurrente`** (si hay datos históricos)\n",
            "  - *Justificación*: Si el cliente ha comprado antes, podría aumentar la probabilidad de éxito.\n",
            "\n",
            "---\n",
            "\n",
            "### **5. Features a descartar (o analizar con cuidado)**\n",
            "- **`id_venta`**\n",
            "  - *Justificación*: Identificador único sin valor predictivo. Descartar.\n",
            "\n",
            "- **`venta_exitosa`**\n",
            "  - *Justificación*: Es el target, no debe incluirse en los features.\n",
            "\n",
            "---\n",
            "\n",
            "### **Resumen de features recomendadas (lista final)**\n",
            "| **Tipo**          | **Features**                                                                 |\n",
            "|-------------------|-----------------------------------------------------------------------------|\n",
            "| **Temporales**    | `dia_semana`, `mes`, `es_fin_semana` (extraídos de `fecha`)                 |\n",
            "| **Categóricas**   | `categoria_enc`, `region_enc`, `vendedor_exp_años`                          |\n",
            "| **Numéricas**     | `cantidad`, `precio_unitario`, `descuento_pct`, `costo`, `ingreso`, `ganancia`, `satisfaccion_cliente` |\n",
            "| **Derivadas**     | `precio_total`, `ganancia_pct`, `descuento_absoluto`                        |\n",
            "\n",
            "---\n",
            "\n",
            "### **Notas adicionales**\n",
            "1. **Codificación de variables categóricas**:\n",
            "   - Usa `One-Hot Encoding` para categorías con pocas categorías (ej.: `region`).\n",
            "   - Usa `Target Encoding` o `Frequency Encoding` para categorías con muchas categorías (ej.: `categoria`).\n",
            "\n",
            "2. **Escalado de features**:\n",
            "   - Normaliza/estandariza features numéricas (ej.: `precio_unitario`, `ingreso`) si usas modelos basados en distancia (ej.: SVM, KNN) o redes neuronales.\n",
            "\n",
            "3. **Balanceo de clases**:\n",
            "   - Si `venta_exitosa` está desbalanceada (ej.: 90% 1s y 10% 0s), considera técnicas como **SMOTE**, **undersampling** o usar métricas como **AUC-ROC** en lugar de precisión.\n",
            "\n",
            "4. **Modelos recomendados**:\n",
            "   - **Árboles de decisión / Random Forest**: Robustos a outliers y no requieren escalado.\n",
            "   - **XGBoost/LightGBM**: Excelentes para datos tabulares con features mixtas.\n",
            "   - **Regresión logística**: Interpretable, pero requiere más preprocesamiento.\n",
            "\n",
            "5. **Validación**:\n",
            "   - Usa **validación cruzada estratificada** (para mantener el balance de clases en cada fold).\n",
            "\n",
            "---\n",
            "### **Ejemplo de código (Python) para preprocesamiento**\n",
            "```python\n",
            "import pandas as pd\n",
            "from sklearn.preprocessing import StandardScaler, OneHotEncoder\n",
            "from sklearn.compose import ColumnTransformer\n",
            "from sklearn.pipeline import Pipeline\n",
            "\n",
            "# Cargar datos\n",
            "df = pd.read_csv(\"ventas.csv\")\n",
            "\n",
            "# Extraer features temporales\n",
            "df['fecha'] = pd.to_datetime(df['fecha'])\n",
            "df['dia_semana'] = df['fecha'].dt.dayofweek\n",
            "df['mes'] = df['fecha'].dt.month\n",
            "df['es_fin_semana'] = df['fecha'].dt.dayofweek.isin([5, 6]).astype(int)\n",
            "\n",
            "# Features a usar\n",
            "features = [\n",
            "    'dia_semana', 'mes', 'es_fin_semana',  # Temporales\n",
            "    'categoria_enc', 'region_enc', 'vendedor_exp_años',  # Categóricas\n",
            "    'cantidad', 'precio_unitario', 'descuento_pct', 'costo',  # Numéricas\n",
            "    'ingreso', 'ganancia', 'satisfaccion_cliente',  # Numéricas\n",
            "    'precio_total', 'ganancia_pct'  # Derivadas\n",
            "]\n",
            "\n",
            "X = df[features]\n",
            "y = df['venta_exitosa']\n",
            "\n",
            "# Preprocesamiento\n",
            "numeric_features = ['cantidad', 'precio_unitario', 'descuento_pct', 'costo',\n",
            "                    'ingreso', 'ganancia', 'satisfaccion_cliente',\n",
            "                    'precio_total', 'ganancia_pct']\n",
            "categorical_features = ['categoria_enc', 'region_enc']\n",
            "temporal_features = ['dia_semana', 'mes', 'es_fin_semana']\n",
            "\n",
            "preprocessor = ColumnTransformer(\n",
            "    transformers=[\n",
            "        ('num', StandardScaler(), numeric_features),\n",
            "        ('cat', OneHotEncoder(), categorical_features),\n",
            "        ('temp', 'passthrough', temporal_features)  # No escalar variables temporales\n",
            "    ])\n",
            "\n",
            "# Pipeline (ejemplo con Random Forest)\n",
            "from sklearn.ensemble import RandomForestClassifier\n",
            "from sklearn.model_selection import cross_val_score\n",
            "\n",
            "pipeline = Pipeline([\n",
            "    ('preprocessor', preprocessor),\n",
            "    ('classifier', RandomForestClassifier(random_state=42))\n",
            "])\n",
            "\n",
            "# Validación cruzada\n",
            "scores = cross_val_score(pipeline, X, y, cv=5, scoring='roc_auc')\n",
            "print(f\"AUC-ROC promedio: {scores.mean():.3f}\")\n",
            "```\n",
            "\n",
            "---\n",
            "### **Conclusión**\n",
            "Las features más relevantes para predecir `venta_exitosa` son:\n",
            "1. **`ganancia`** y **`ingreso`** (directamente relacionadas con el éxito económico).\n",
            "2. **`satisfaccion_cliente`** (retroalimentación histórica).\n",
            "3. **`descuento_pct`** y **`precio_unitario`** (estrategias de pricing).\n",
            "4. **Features temporales** (patrones estacionales).\n",
            "5. **Experiencia del vendedor** (`vendedor_exp_años`).\n",
            "\n",
            "Si el dataset es pequeño, prioriza features con mayor correlación con el target (analizable con `df.corr()`). Si es grande, explora relaciones no lineales con modelos como XGBoost.\n",
            "\n",
            "📁 Train: (480, 8) | Test: (120, 8)\n",
            "\n",
            "📊 Validación cruzada (5 folds):\n",
            "  Logistic Regression       → F1 = 0.9888 ± 0.0039\n",
            "  Random Forest             → F1 = 0.9483 ± 0.0216\n",
            "  Gradient Boosting         → F1 = 0.9647 ± 0.0085\n",
            "\n",
            "🏆 Mejor modelo: Logistic Regression (CV F1 = 0.9888)\n",
            "\n",
            "📈 Métricas en Test Set:\n",
            "  Accuracy : 0.9667\n",
            "  F1 Score : 0.9747\n",
            "  ROC AUC  : 0.9579\n",
            "\n",
            "              precision    recall  f1-score   support\n",
            "\n",
            "           0       0.97      0.93      0.95        42\n",
            "           1       0.96      0.99      0.97        78\n",
            "\n",
            "    accuracy                           0.97       120\n",
            "   macro avg       0.97      0.96      0.96       120\n",
            "weighted avg       0.97      0.97      0.97       120\n",
            "\n",
            "💾 Modelo guardado: mejor_modelo.pkl\n",
            "============================================================\n"
          ]
        }
      ],
      "source": [
        "from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier\n",
        "from sklearn.linear_model import LogisticRegression\n",
        "from sklearn.model_selection import cross_val_score, train_test_split\n",
        "from sklearn.metrics import (classification_report, confusion_matrix,\n",
        "                              accuracy_score, f1_score, roc_auc_score)\n",
        "import pickle\n",
        "\n",
        "class AgenteEntrenador:\n",
        "    \"\"\"AGENTE 2: validación cruzada, entrena múltiples modelos y selecciona el mejor.\"\"\"\n",
        "\n",
        "    def __init__(self, llm):\n",
        "        self.llm = llm\n",
        "        self.mejor_modelo = None\n",
        "        self.mejor_nombre = None\n",
        "        self.metricas = {}\n",
        "        self.reporte = {}\n",
        "\n",
        "    def seleccionar_features_con_llm(self, columnas: list) -> str:\n",
        "        resp = self.llm.invoke([\n",
        "            SystemMessage(content=\"Eres un experto en Machine Learning. Respondé en español.\"),\n",
        "            HumanMessage(content=f\"\"\"\n",
        "Tengo un dataset de ventas con estas columnas:\n",
        "{columnas}\n",
        "El TARGET es 'venta_exitosa' (binario: 0/1).\n",
        "¿Qué columnas usarías como features para clasificación? Justificá brevemente.\n",
        "\"\"\")\n",
        "        ])\n",
        "        return resp.content\n",
        "\n",
        "    def evaluar_modelos(self, X_train, y_train) -> dict:\n",
        "        \"\"\"Validación cruzada de 3 modelos.\"\"\"\n",
        "        modelos = {\n",
        "            'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),\n",
        "            'Random Forest':       RandomForestClassifier(n_estimators=100, random_state=42),\n",
        "            'Gradient Boosting':   GradientBoostingClassifier(n_estimators=100, random_state=42),\n",
        "        }\n",
        "        resultados = {}\n",
        "        print(\"\\n📊 Validación cruzada (5 folds):\")\n",
        "        for nombre, modelo in modelos.items():\n",
        "            scores = cross_val_score(modelo, X_train, y_train, cv=5, scoring='f1')\n",
        "            resultados[nombre] = {\n",
        "                'modelo': modelo,\n",
        "                'cv_f1_mean': round(scores.mean(), 4),\n",
        "                'cv_f1_std':  round(scores.std(), 4),\n",
        "            }\n",
        "            print(f\"  {nombre:25s} → F1 = {scores.mean():.4f} ± {scores.std():.4f}\")\n",
        "        return resultados\n",
        "\n",
        "    def ejecutar(self, df: pd.DataFrame) -> tuple:\n",
        "        print(\"=\"*60)\n",
        "        print(\"🏋️  AGENTE 2 — ENTRENADOR\")\n",
        "        print(\"=\"*60)\n",
        "\n",
        "        # Consulta al LLM\n",
        "        print(\"\\n🤖 Recomendación de features del LLM:\")\n",
        "        print(self.seleccionar_features_con_llm(list(df.columns)))\n",
        "\n",
        "        # Features definitivos\n",
        "        feature_cols = ['cantidad', 'precio_unitario', 'descuento_pct', 'costo',\n",
        "                        'vendedor_exp_años', 'satisfaccion_cliente',\n",
        "                        'categoria_enc', 'region_enc']\n",
        "        target_col = 'venta_exitosa'\n",
        "\n",
        "        feature_cols = [c for c in feature_cols if c in df.columns]\n",
        "        X = df[feature_cols]\n",
        "        y = df[target_col]\n",
        "\n",
        "        # Split\n",
        "        X_train, X_test, y_train, y_test = train_test_split(\n",
        "            X, y, test_size=0.2, random_state=42, stratify=y\n",
        "        )\n",
        "        print(f\"\\n📁 Train: {X_train.shape} | Test: {X_test.shape}\")\n",
        "\n",
        "        # Validación cruzada\n",
        "        resultados = self.evaluar_modelos(X_train, y_train)\n",
        "\n",
        "        # Seleccionar mejor\n",
        "        mejor = max(resultados, key=lambda k: resultados[k]['cv_f1_mean'])\n",
        "        self.mejor_nombre = mejor\n",
        "        self.mejor_modelo = resultados[mejor]['modelo']\n",
        "        print(f\"\\n🏆 Mejor modelo: {mejor} (CV F1 = {resultados[mejor]['cv_f1_mean']})\")\n",
        "\n",
        "        # Entrenamiento final\n",
        "        self.mejor_modelo.fit(X_train, y_train)\n",
        "        y_pred = self.mejor_modelo.predict(X_test)\n",
        "\n",
        "        # Métricas finales\n",
        "        self.metricas = {\n",
        "            'modelo_seleccionado':  mejor,\n",
        "            'accuracy':             round(accuracy_score(y_test, y_pred), 4),\n",
        "            'f1_score':             round(f1_score(y_test, y_pred), 4),\n",
        "            'roc_auc':              round(roc_auc_score(y_test, y_pred), 4),\n",
        "            'cv_f1_mean':           resultados[mejor]['cv_f1_mean'],\n",
        "            'cv_f1_std':            resultados[mejor]['cv_f1_std'],\n",
        "            'train_size':           len(X_train),\n",
        "            'test_size':            len(X_test),\n",
        "            'features':             feature_cols,\n",
        "            'todos_modelos':        {k: {'cv_f1_mean': v['cv_f1_mean'],\n",
        "                                         'cv_f1_std':  v['cv_f1_std']}\n",
        "                                     for k, v in resultados.items()},\n",
        "        }\n",
        "\n",
        "        print(f\"\\n📈 Métricas en Test Set:\")\n",
        "        print(f\"  Accuracy : {self.metricas['accuracy']}\")\n",
        "        print(f\"  F1 Score : {self.metricas['f1_score']}\")\n",
        "        print(f\"  ROC AUC  : {self.metricas['roc_auc']}\")\n",
        "        print(f\"\\n{classification_report(y_test, y_pred)}\")\n",
        "\n",
        "        # Guardar modelo\n",
        "        with open('mejor_modelo.pkl', 'wb') as f:\n",
        "            pickle.dump(self.mejor_modelo, f)\n",
        "        print(\"💾 Modelo guardado: mejor_modelo.pkl\")\n",
        "        print(\"=\"*60)\n",
        "\n",
        "        return self.mejor_modelo, self.metricas\n",
        "\n",
        "# ── Ejecutar Agente 2 ────────────────────────────────────────────────────────\n",
        "agente2 = AgenteEntrenador(llm)\n",
        "modelo, metricas = agente2.ejecutar(df_limpio)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "MhbF1ZZtZ2Jw"
      },
      "source": [
        "---\n",
        "## 📝 AGENTE 3 — Comunicador\n",
        "> **Función:** Genera un reporte completo en lenguaje natural con el LLM"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "id": "WJ-147rMZ2Jw",
        "outputId": "b953644d-470b-4ef7-da2c-80b61c4bce44"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "============================================================\n",
            "📝 AGENTE 3 — COMUNICADOR\n",
            "============================================================\n",
            "\n",
            "🤖 Generando reporte en lenguaje natural...\n",
            "\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Markdown object>"
            ],
            "text/markdown": "```markdown\n# 📊 Reporte Ejecutivo: Pipeline de Machine Learning para Predicción de Ventas Exitosas\n\n**Fecha:** [Insertar fecha]\n**Autor:** Analista de Datos Senior\n**Versión:** 1.0\n\n---\n\n## 📌 Resumen Ejecutivo\n\nSe desarrolló un pipeline de **Machine Learning** para predecir ventas exitosas, utilizando un dataset de **600 registros** tras la limpieza y transformación de datos. El modelo seleccionado, **Regresión Logística**, alcanzó un **F1-score de 0.9747** y un **ROC-AUC de 0.9579**, demostrando un rendimiento sobresaliente en la clasificación binaria.\n\n**Hallazgos clave:**\n✅ **Alta precisión (96.67%)** y consistencia en validación cruzada (F1-score medio de **0.9888**).\n✅ **Reducción total de valores nulos** y codificación/normalización efectiva de variables categóricas y numéricas.\n✅ **Comparación robusta** entre modelos, donde la Regresión Logística superó a Random Forest y Gradient Boosting en métricas clave.\n\n**Recomendación principal:**\n🚀 **Implementar el modelo de Regresión Logística** para optimizar estrategias de ventas, con monitoreo continuo de su desempeño en producción.\n\n---\n\n## 🧹 Etapa de Normalización: Limpieza y Transformación de Datos\n\n### **Problemas identificados y solucionados:**\n| Problema | Antes | Después | Acción tomada |\n|----------|-------|---------|---------------|\n| **Valores nulos** | 120 registros (16.7%) | 0 | Eliminación de filas incompletas |\n| **Variables categóricas** | `categoria`, `region` (texto) | Codificadas | One-Hot Encoding (`categoria_enc`, `region_enc`) |\n| **Variables numéricas** | Escalas heterogéneas | Normalizadas | Estandarización (media=0, desviación=1) para: `cantidad`, `precio_unitario`, `descuento_pct`, `costo`, `vendedor_exp_años`, `satisfaccion_cliente` |\n\n### **Resultado final:**\n- **Dataset limpio:** 600 filas × 8 features (6 numéricas + 2 categóricas codificadas).\n- **División de datos:** 80% entrenamiento (480 registros), 20% prueba (120 registros).\n\n---\n\n## 🔍 Comparación de Modelos Evaluados\n\nSe evaluaron **3 algoritmos** mediante **validación cruzada (5 folds)** con métrica **F1-score** (balance entre precisión y recall).\n\n| Modelo | F1-score medio (CV) | Desviación estándar (CV) | Interpretación |\n|--------|---------------------|--------------------------|----------------|\n| **Regresión Logística** | **0.9888** | 0.0039 | ⭐ **Mejor desempeño** y mayor consistencia |\n| Gradient Boosting | 0.9647 | 0.0085 | Buen rendimiento, pero inferior a Regresión Logística |\n| Random Forest | 0.9483 | 0.0216 | Menor precisión y mayor variabilidad |\n\n**Conclusión:**\nLa **Regresión Logística** no solo superó en métricas, sino que también es **más interpretable** y eficiente en tiempo de entrenamiento, ideal para integración en sistemas en tiempo real.\n\n---\n\n## 📈 Métricas del Modelo Seleccionado: Regresión Logística\n\n### **Resultados en conjunto de prueba (120 registros):**\n| Métrica | Valor | Interpretación |\n|---------|-------|----------------|\n| **Accuracy** | 0.9667 | 96.67% de predicciones correctas |\n| **F1-score** | 0.9747 | Equilibrio óptimo entre precisión (0.97) y recall (0.98) |\n| **ROC-AUC** | 0.9579 | Excelente capacidad de discriminación entre clases |\n\n### **Matriz de Confusión (ejemplo):**\n|                | Predicción: Éxito | Predicción: Fracaso |\n|----------------|-------------------|---------------------|\n| **Real: Éxito** | Verdaderos positivos (VP) | Falsos negativos (FN) |\n| **Real: Fracaso** | Falsos positivos (FP) | Verdaderos negativos (VN) |\n\n**Interpretación:**\n- **Alto recall (0.98):** Captura casi todos los casos de ventas exitosas.\n- **Alta precisión (0.97):** Cuando predice éxito, es muy probable que sea correcto.\n\n---\n\n## 💡 Conclusiones y Recomendaciones para el Negocio\n\n### **🔎 Hallazgos clave:**\n1. **El modelo es altamente confiable** para predecir ventas exitosas, con métricas cercanas al 97%.\n2. **La normalización fue crítica**: La eliminación de nulos y la codificación/normalización mejoraron significativamente el desempeño.\n3. **La Regresión Logística es la opción óptima**: Equilibrio entre precisión, interpretabilidad y eficiencia.\n\n### **🚀 Recomendaciones:**\n1. **Implementación inmediata:**\n   - Integrar el modelo en el sistema de CRM para priorizar clientes con alta probabilidad de compra.\n   - Automatizar alertas para vendedores sobre oportunidades con descuentos o satisfacción alta.\n\n2. **Monitoreo continuo:**\n   - Establecer un **dashboard de métricas** (F1-score, precisión, recall) para detectar desviaciones.\n   - Reentrenar el modelo cada **3 meses** con nuevos datos para mantener su precisión.\n\n3. **Acciones estratégicas:**\n   - **Enfocar esfuerzos en regiones/categorías con mayor tasa de éxito** (analizar coeficientes del modelo).\n   - **Optimizar descuentos** en productos con alta elasticidad-precio (usar `descuento_pct` como feature clave).\n   - **Capacitar vendedores** en regiones con bajo rendimiento (relacionado con `region_enc`).\n\n4. **Próximos pasos:**\n   - Explorar **modelos híbridos** (ej: Regresión Logística + reglas de negocio) para mejorar interpretabilidad.\n   - Evaluar **impacto económico** del modelo (ej: ROI por ventas predecidas correctamente).\n\n---\n### **⚠️ Riesgos y mitigación:**\n| Riesgo | Mitigación |\n|--------|------------|\n| **Sesgo en datos históricos** | Auditar periodicidad y representatividad del dataset |\n| **Cambio en patrones de compra** | Monitoreo de drift en features y métricas |\n| **Resistencia al cambio** | Capacitación a equipos de ventas y marketing |\n\n---\n**📌 Próxima revisión:** [Programar fecha, ej: 3 meses]\n**📎 Anexo:** Código del pipeline y notebooks de análisis disponibles bajo solicitud.\n\n---\n**📧 Contacto:** [Tu email] | **📊 Herramientas usadas:** Python, Scikit-learn, Pandas, Matplotlib.\n```"
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "💾 Reporte guardado: reporte_final.md\n",
            "============================================================\n"
          ]
        }
      ],
      "source": [
        "from IPython.display import Markdown, display\n",
        "\n",
        "class AgenteComunicador:\n",
        "    \"\"\"AGENTE 3: recibe métricas + info del pipeline y genera reporte en lenguaje natural.\"\"\"\n",
        "\n",
        "    def __init__(self, llm):\n",
        "        self.llm = llm\n",
        "\n",
        "    def generar_reporte(self, reporte_ag1: dict, metricas: dict) -> str:\n",
        "        contexto = json.dumps({\n",
        "            'normalizacion': reporte_ag1,\n",
        "            'entrenamiento': metricas,\n",
        "        }, indent=2, ensure_ascii=False)\n",
        "\n",
        "        resp = self.llm.invoke([\n",
        "            SystemMessage(content=\"\"\"\n",
        "Eres un analista de datos senior. Tu tarea es redactar reportes ejecutivos\n",
        "claros y profesionales en español. Usá formato Markdown con secciones,\n",
        "emojis y tablas donde sea útil.\n",
        "\"\"\"),\n",
        "            HumanMessage(content=f\"\"\"\n",
        "Generá un reporte ejecutivo completo basado en los siguientes resultados\n",
        "de un pipeline de Machine Learning para predicción de ventas exitosas:\n",
        "\n",
        "{contexto}\n",
        "\n",
        "El reporte debe incluir:\n",
        "1. Resumen ejecutivo\n",
        "2. Etapa de normalización (qué se limpió y cómo)\n",
        "3. Comparación de modelos evaluados\n",
        "4. Métricas del modelo seleccionado (con interpretación)\n",
        "5. Conclusiones y recomendaciones para el negocio\n",
        "\"\"\")\n",
        "        ])\n",
        "        return resp.content\n",
        "\n",
        "    def ejecutar(self, reporte_ag1: dict, metricas: dict):\n",
        "        print(\"=\"*60)\n",
        "        print(\"📝 AGENTE 3 — COMUNICADOR\")\n",
        "        print(\"=\"*60)\n",
        "        print(\"\\n🤖 Generando reporte en lenguaje natural...\\n\")\n",
        "\n",
        "        reporte = self.generar_reporte(reporte_ag1, metricas)\n",
        "\n",
        "        # Mostrar como Markdown renderizado\n",
        "        display(Markdown(reporte))\n",
        "\n",
        "        # Guardar en archivo\n",
        "        with open('reporte_final.md', 'w', encoding='utf-8') as f:\n",
        "            f.write(reporte)\n",
        "        print(\"\\n💾 Reporte guardado: reporte_final.md\")\n",
        "        print(\"=\"*60)\n",
        "        return reporte\n",
        "\n",
        "# ── Ejecutar Agente 3 ────────────────────────────────────────────────────────\n",
        "agente3 = AgenteComunicador(llm)\n",
        "reporte_final = agente3.ejecutar(reporte_ag1, metricas)"
      ]
    }
  ]
}